# Generated by Django 4.2.28 on 2026-03-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN', 'In'), ('OUT', 'Out')], default='PENDING', max_length=10)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.resident')),
            ],
        ),
    ]
