# Generated by Django 4.2.28 on 2026-03-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN', 'In'), ('OUT', 'Out')], default='PENDING', max_length=10),
        ),
    ]
